name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsystemd-dev
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"
    - name: Analysing the code with pylint
      run: |
        pylint -d duplicate-code $(git ls-files '*.py')
